# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name:		sugar-browse-activity
Version:	156
Release:	2
Summary:	Browse activity for Sugar
License:	GPLv2+
Group:		Graphical desktop/Other
Url:		http://sugarlabs.org/

Source:		http://download.sugarlabs.org/sources/sucrose/fructose/Browse/Browse-%{version}.tar.bz2

Requires:	python-cjson  
Requires:	sugar-toolkit-gtk3 >= 0.88.0

BuildRequires:	gettext  
BuildRequires:	python-devel  
BuildRequires:	sugar-toolkit-gtk3 >= 0.88.0

BuildArch:	noarch

%description
Browse is a Web browser built on WebKit.

%prep
%setup -q -n Browse-%{version}

%build

rm -f MANIFEST
python setup.py build

%install
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.WebActivity

%files -f org.laptop.WebActivity.lang
%doc AUTHORS COPYING
%{_datadir}/sugar/activities/*

